


version: '3.7'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - KAFKA_BROKER=kafka:9092
      - CASSANDRA_HOST=cassandra
    networks:
      - my-network

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - KAFKA_BROKER=kafka:9092
      - CASSANDRA_HOST=cassandra
    depends_on:
      - spark-master
    networks:
      - my-network

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - KAFKA_BROKER=kafka:9092
      - CASSANDRA_HOST=cassandra
    depends_on:
      - spark-master
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - my-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - my-network

  hadoop-namenode:
    image: "bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8"
    container_name: "hadoop-namenode"
    environment:
      - CLUSTER_NAME=hadoop-cluster
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode_data:/hadoop/dfs/namenode
    networks:
      - my-network

  hadoop-datanode:
    image: "bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8"
    container_name: "hadoop-datanode"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    ports:
      - "9864:9864"
    volumes:
      - datanode_data:/hadoop/dfs/datanode
    depends_on:
      - hadoop-namenode
    networks:
      - my-network

volumes:
  namenode_data:
  datanode_data:

networks:
  my-network:
    driver: bridge